// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetSpotifyPlaylistEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/spotify/playlist';
};

export type GetSpotifyPlaylistEndpointErrors = {
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type GetSpotifyPlaylistEndpointError = GetSpotifyPlaylistEndpointErrors[keyof GetSpotifyPlaylistEndpointErrors];

export type GetSpotifyPlaylistEndpointResponses = {
    /**
     * Successful response with playlist data
     */
    200: {
        id: string;
        name: string;
        description?: string | null;
        images: Array<{
            url: string;
            height: number | null;
            width: number | null;
        }>;
        tracks: Array<{
            id: string;
            name: string;
            artists: string;
            duration_ms: number;
            external_url: string | null;
            album: string | null;
        }>;
    };
};

export type GetSpotifyPlaylistEndpointResponse = GetSpotifyPlaylistEndpointResponses[keyof GetSpotifyPlaylistEndpointResponses];

export type GetSpotifyOwnershipEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/spotify/ownership';
};

export type GetSpotifyOwnershipEndpointErrors = {
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type GetSpotifyOwnershipEndpointError = GetSpotifyOwnershipEndpointErrors[keyof GetSpotifyOwnershipEndpointErrors];

export type GetSpotifyOwnershipEndpointResponses = {
    /**
     * Successful response with ownership data
     */
    200: {
        ownership: {
            [key: string]: {
                addedBy: {
                    twitchId: string;
                    displayName: string;
                };
            };
        };
        cached: boolean;
    };
};

export type GetSpotifyOwnershipEndpointResponse = GetSpotifyOwnershipEndpointResponses[keyof GetSpotifyOwnershipEndpointResponses];

export type PostLoginEndpointData = {
    body?: {
        code: string;
        redirectURL: string;
    };
    path?: never;
    query?: never;
    url: '/api/login';
};

export type PostLoginEndpointErrors = {
    /**
     * Bad request
     */
    400: {
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type PostLoginEndpointError = PostLoginEndpointErrors[keyof PostLoginEndpointErrors];

export type PostLoginEndpointResponses = {
    /**
     * Successful login
     */
    200: {
        success: true;
        message: string;
        data: {
            twitchID: string;
            twitchUsername: string;
            sessionId: string;
            isSubscriber: boolean;
        };
    };
};

export type PostLoginEndpointResponse = PostLoginEndpointResponses[keyof PostLoginEndpointResponses];

export type PostAdminTwitchCallbackEndpointData = {
    body?: {
        code: string;
        redirectURL: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/twitch/callback';
};

export type PostAdminTwitchCallbackEndpointErrors = {
    /**
     * Bad request, missing code or redirectURL
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized, not the channel owner
     */
    403: {
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type PostAdminTwitchCallbackEndpointError = PostAdminTwitchCallbackEndpointErrors[keyof PostAdminTwitchCallbackEndpointErrors];

export type PostAdminTwitchCallbackEndpointResponses = {
    /**
     * Successfully authenticated with Twitch
     */
    200: {
        success: boolean;
        data: {
            id: string;
            display_name: string;
        };
    };
};

export type PostAdminTwitchCallbackEndpointResponse = PostAdminTwitchCallbackEndpointResponses[keyof PostAdminTwitchCallbackEndpointResponses];

export type GetAdminTwitchInfoEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/twitch/info';
};

export type GetAdminTwitchInfoEndpointErrors = {
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type GetAdminTwitchInfoEndpointError = GetAdminTwitchInfoEndpointErrors[keyof GetAdminTwitchInfoEndpointErrors];

export type GetAdminTwitchInfoEndpointResponses = {
    /**
     * Successful response with Twitch admin info
     */
    200: {
        success: true;
        data: {
            id: string;
            display_name: string;
            scope: Array<string>;
            obtained_at: number;
        } | null;
    };
};

export type GetAdminTwitchInfoEndpointResponse = GetAdminTwitchInfoEndpointResponses[keyof GetAdminTwitchInfoEndpointResponses];

export type PostAdminSpotifyCallbackEndpointData = {
    body?: {
        code: string;
        redirectURL: string;
        sessionId: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/spotify/callback';
};

export type PostAdminSpotifyCallbackEndpointErrors = {
    /**
     * Bad request
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    403: {
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type PostAdminSpotifyCallbackEndpointError = PostAdminSpotifyCallbackEndpointErrors[keyof PostAdminSpotifyCallbackEndpointErrors];

export type PostAdminSpotifyCallbackEndpointResponses = {
    /**
     * Successful authentication
     */
    200: {
        success: boolean;
        data: {
            expiresIn: number;
        };
    };
};

export type PostAdminSpotifyCallbackEndpointResponse = PostAdminSpotifyCallbackEndpointResponses[keyof PostAdminSpotifyCallbackEndpointResponses];

export type GetAdminSpotifyInfoEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/spotify/info';
};

export type GetAdminSpotifyInfoEndpointErrors = {
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type GetAdminSpotifyInfoEndpointError = GetAdminSpotifyInfoEndpointErrors[keyof GetAdminSpotifyInfoEndpointErrors];

export type GetAdminSpotifyInfoEndpointResponses = {
    /**
     * Authentication status retrieved successfully
     */
    200: {
        success: boolean;
        data: boolean;
    };
};

export type GetAdminSpotifyInfoEndpointResponse = GetAdminSpotifyInfoEndpointResponses[keyof GetAdminSpotifyInfoEndpointResponses];

export type PostBanUserEndpointData = {
    body?: {
        twitchId: string;
        action: 'ban' | 'unban';
        sessionId: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/ban-user';
};

export type PostBanUserEndpointErrors = {
    /**
     * Bad request
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    403: {
        message: string;
    };
    /**
     * User not found
     */
    404: {
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type PostBanUserEndpointError = PostBanUserEndpointErrors[keyof PostBanUserEndpointErrors];

export type PostBanUserEndpointResponses = {
    /**
     * User banned or unbanned successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            twitchId: string;
            displayName: string;
            isBanned: boolean;
        };
    };
};

export type PostBanUserEndpointResponse = PostBanUserEndpointResponses[keyof PostBanUserEndpointResponses];

export type PostClearCacheEndpointData = {
    body?: {
        sessionId: string;
        cacheType: 'playlist' | 'ownership' | 'all';
    };
    path?: never;
    query?: never;
    url: '/api/admin/clear-cache';
};

export type PostClearCacheEndpointErrors = {
    /**
     * Bad request
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    403: {
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type PostClearCacheEndpointError = PostClearCacheEndpointErrors[keyof PostClearCacheEndpointErrors];

export type PostClearCacheEndpointResponses = {
    /**
     * Cache cleared successfully
     */
    200: {
        success: boolean;
        message: string;
        clearedCaches: Array<'playlist' | 'ownership'>;
    };
};

export type PostClearCacheEndpointResponse = PostClearCacheEndpointResponses[keyof PostClearCacheEndpointResponses];

export type PostSetTrustedUserEndpointData = {
    body?: {
        sessionId: string;
        targetTwitchId: string;
        isTrusted: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/admin/set-trusted-user';
};

export type PostSetTrustedUserEndpointErrors = {
    /**
     * Bad request
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized
     */
    401: {
        message: string;
    };
    /**
     * Forbidden
     */
    403: {
        message: string;
    };
    /**
     * User not found
     */
    404: {
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        message: string;
    };
};

export type PostSetTrustedUserEndpointError = PostSetTrustedUserEndpointErrors[keyof PostSetTrustedUserEndpointErrors];

export type PostSetTrustedUserEndpointResponses = {
    /**
     * Trusted user status updated successfully
     */
    200: {
        success: boolean;
        account: {
            twitch_id: string;
            display_name: string;
            is_owner: boolean;
            is_trusted: boolean;
        };
    };
};

export type PostSetTrustedUserEndpointResponse = PostSetTrustedUserEndpointResponses[keyof PostSetTrustedUserEndpointResponses];

export type GetIsAdminEndpointData = {
    body?: never;
    path?: never;
    query: {
        sessionId: string;
    };
    url: '/api/admin/is-admin';
};

export type GetIsAdminEndpointResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PostEventSubCallbackEndpointData = {
    body?: never;
    headers: {
        'Twitch-Eventsub-Message-Type': string;
        'Twitch-Eventsub-Message-Id': string;
        'Twitch-Eventsub-Message-Timestamp': string;
        'Twitch-Eventsub-Message-Signature': string;
    };
    path?: never;
    query?: never;
    url: '/api/eventsub/callback';
};

export type PostEventSubCallbackEndpointErrors = {
    /**
     * Bad request
     */
    400: {
        message: string;
    };
    /**
     * Forbidden
     */
    403: {
        message: string;
    };
};

export type PostEventSubCallbackEndpointError = PostEventSubCallbackEndpointErrors[keyof PostEventSubCallbackEndpointErrors];

export type PostEventSubCallbackEndpointResponses = {
    /**
     * Success
     */
    200: string;
};

export type PostEventSubCallbackEndpointResponse = PostEventSubCallbackEndpointResponses[keyof PostEventSubCallbackEndpointResponses];

export type GetGetAccountSessionEndpointData = {
    body?: never;
    path?: never;
    query: {
        sessionId: string;
    };
    url: '/api/accounts/session';
};

export type GetGetAccountSessionEndpointResponses = {
    /**
     * Success
     */
    200: {
        success: boolean;
        account: {
            is_subscriber: boolean;
            twitch_id: string;
            is_owner: boolean;
        };
    };
};

export type GetGetAccountSessionEndpointResponse = GetGetAccountSessionEndpointResponses[keyof GetGetAccountSessionEndpointResponses];

export type GetListApologiesEndpointData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        pageSize?: string;
    };
    url: '/api/apologies';
};

export type GetListApologiesEndpointResponses = {
    /**
     * Success
     */
    200: {
        items: Array<unknown>;
        total: number;
        page: number;
        pageSize: number;
    };
};

export type GetListApologiesEndpointResponse = GetListApologiesEndpointResponses[keyof GetListApologiesEndpointResponses];

export type PostSubmitApologyEndpointData = {
    body?: {
        sessionId: string;
        apology: string;
        subject: string;
    };
    path?: never;
    query?: never;
    url: '/api/apologies';
};

export type PostSubmitApologyEndpointResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetGetApologyEndpointData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/apologies/{id}';
};

export type GetGetApologyEndpointResponses = {
    /**
     * Success
     */
    200: {
        success: boolean;
        username: string;
        subject: string;
        apology: string;
    };
};

export type GetGetApologyEndpointResponse = GetGetApologyEndpointResponses[keyof GetGetApologyEndpointResponses];

export type PostSpotifyAddTrackEndpointData = {
    body?: {
        sessionId: string;
        trackUri: string;
    };
    path?: never;
    query?: never;
    url: '/api/spotify/playlist/add';
};

export type PostSpotifyAddTrackEndpointResponses = {
    /**
     * Track added successfully or pending approval
     */
    200: {
        success: boolean;
        pending?: boolean;
        addedDirectly?: boolean;
        message?: string;
    };
};

export type PostSpotifyAddTrackEndpointResponse = PostSpotifyAddTrackEndpointResponses[keyof PostSpotifyAddTrackEndpointResponses];

export type PostSpotifyRemoveTrackEndpointData = {
    body?: {
        sessionId: string;
        trackUri: string;
    };
    path?: never;
    query?: never;
    url: '/api/spotify/playlist/remove';
};

export type PostSpotifyRemoveTrackEndpointResponses = {
    /**
     * Track removed successfully
     */
    200: {
        success: boolean;
        message?: string;
    };
};

export type PostSpotifyRemoveTrackEndpointResponse = PostSpotifyRemoveTrackEndpointResponses[keyof PostSpotifyRemoveTrackEndpointResponses];

export type GetSpotifyPendingSongsEndpointData = {
    body?: never;
    path?: never;
    query: {
        sessionId: string;
    };
    url: '/api/spotify/playlist/pending';
};

export type GetSpotifyPendingSongsEndpointResponses = {
    /**
     * List of pending songs
     */
    200: {
        pendingSongs: Array<{
            id: string;
            title: string;
            artist: string;
            album: string;
            coverUrl: string;
        }>;
    };
};

export type GetSpotifyPendingSongsEndpointResponse = GetSpotifyPendingSongsEndpointResponses[keyof GetSpotifyPendingSongsEndpointResponses];

export type PostSpotifyApproveSongEndpointData = {
    body?: {
        sessionId: string;
        spotifyId: string;
    };
    path?: never;
    query?: never;
    url: '/api/spotify/playlist/approve';
};

export type PostSpotifyApproveSongEndpointResponses = {
    /**
     * Song approved and added to playlist
     */
    200: {
        message: string;
    };
};

export type PostSpotifyApproveSongEndpointResponse = PostSpotifyApproveSongEndpointResponses[keyof PostSpotifyApproveSongEndpointResponses];

export type PostSpotifyDisapproveSongEndpointData = {
    body?: {
        sessionId: string;
        spotifyId: string;
    };
    path?: never;
    query?: never;
    url: '/api/spotify/playlist/disapprove';
};

export type PostSpotifyDisapproveSongEndpointResponses = {
    /**
     * Song disapproved and removed from pending
     */
    200: {
        success: boolean;
    };
};

export type PostSpotifyDisapproveSongEndpointResponse = PostSpotifyDisapproveSongEndpointResponses[keyof PostSpotifyDisapproveSongEndpointResponses];

export type GetCommandSpotifyNowPlayingEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/command/now-playing';
};

export type GetCommandSpotifyNowPlayingEndpointResponses = {
    /**
     * The currently playing Spotify track
     */
    200: string;
};

export type GetCommandSpotifyNowPlayingEndpointResponse = GetCommandSpotifyNowPlayingEndpointResponses[keyof GetCommandSpotifyNowPlayingEndpointResponses];

export type GetExtensionSpotifyNowPlayingEndpointData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/extension/spotify/now-playing';
};

export type GetExtensionSpotifyNowPlayingEndpointResponses = {
    /**
     * The currently playing Spotify track
     */
    200: {
        track: {
            artists: Array<{
                external_urls: {
                    spotify: string;
                };
                href: string;
                id: string;
                name: string;
                type: string;
                uri: string;
            }>;
            title: string;
            addedBy?: string;
        } | null;
    };
};

export type GetExtensionSpotifyNowPlayingEndpointResponse = GetExtensionSpotifyNowPlayingEndpointResponses[keyof GetExtensionSpotifyNowPlayingEndpointResponses];

export type GetOverlaySpotifyNowPlayingEndpointData = {
    body?: never;
    path?: never;
    query: {
        secretAugustKey: string;
    };
    url: '/api/overlay/spotify/now-playing';
};

export type GetOverlaySpotifyNowPlayingEndpointResponses = {
    /**
     * The currently playing Spotify track
     */
    200: {
        track: {
            artists: Array<{
                external_urls: {
                    spotify: string;
                };
                href: string;
                id: string;
                name: string;
                type: string;
                uri: string;
            }>;
            title: string;
            addedBy?: string;
            image: {
                url: string;
                width: number | null;
                height: number | null;
            } | null;
            remainingDurationMs?: number;
        } | null;
    };
};

export type GetOverlaySpotifyNowPlayingEndpointResponse = GetOverlaySpotifyNowPlayingEndpointResponses[keyof GetOverlaySpotifyNowPlayingEndpointResponses];
